-- MySQL Script generated by MySQL Workbench
-- 02/22/16 16:19:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pseudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pseudo` (
  `IdPseudo` INT NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`IdPseudo`),
  UNIQUE INDEX `Pseudo_UNIQUE` (`Pseudo` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MotDePasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MotDePasse` (
  `IdMDP` INT NOT NULL AUTO_INCREMENT,
  `MotDePasse` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdMDP`),
  UNIQUE INDEX `MotDePasse_UNIQUE` (`MotDePasse` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avatar` (
  `IdAvatar` INT NOT NULL AUTO_INCREMENT,
  `Avatar` VARCHAR(45) NULL,
  PRIMARY KEY (`IdAvatar`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Individu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Individu` (
  `Pseudo` INT NOT NULL,
  `MotDePasse` INT NOT NULL,
  `Avatar` INT NOT NULL,
  `Competence` INT NULL,
  `Specialite` INT NULL,
  INDEX `fk_Individu_Pseudo_idx` (`Pseudo` ASC),
  INDEX `fk_Individu_MotDePasse1_idx` (`MotDePasse` ASC),
  UNIQUE INDEX `MotDePasse_IdMDP_UNIQUE` (`MotDePasse` ASC),
  INDEX `fk_Individu_Avatar1_idx` (`Avatar` ASC),
  PRIMARY KEY (`Pseudo`),
  CONSTRAINT `fk_Individu_Pseudo`
  FOREIGN KEY (`Pseudo`)
  REFERENCES `mydb`.`Pseudo` (`IdPseudo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Individu_MotDePasse1`
  FOREIGN KEY (`MotDePasse`)
  REFERENCES `mydb`.`MotDePasse` (`IdMDP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Individu_Avatar1`
  FOREIGN KEY (`Avatar`)
  REFERENCES `mydb`.`Avatar` (`IdAvatar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  KEY_BLOCK_SIZE = 2;


-- -----------------------------------------------------
-- Table `mydb`.`Specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialite` (
  `IdSpecialite` INT NOT NULL AUTO_INCREMENT,
  `Specialite` VARCHAR(45) NOT NULL,
  `Score` INT NULL,
  PRIMARY KEY (`IdSpecialite`),
  CONSTRAINT `fk_Specialite_Individu1`
  FOREIGN KEY (`IdSpecialite`)
  REFERENCES `mydb`.`Individu` (`Specialite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Score` (
  `IdScore` INT NOT NULL AUTO_INCREMENT,
  `Score` INT NULL,
  PRIMARY KEY (`IdScore`),
  CONSTRAINT `fk_Score_Specialite1`
  FOREIGN KEY (`IdScore`)
  REFERENCES `mydb`.`Specialite` (`Score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competence` (
  `IdCompetence` INT NOT NULL AUTO_INCREMENT,
  `Competence` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCompetence`),
  CONSTRAINT `fk_Competence_Individu1`
  FOREIGN KEY (`IdCompetence`)
  REFERENCES `mydb`.`Individu` (`Competence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;